app = "private-chat-app"

[build]
  builder = "heroku/buildpacks:nodejs"

[env]
  PORT = "3000"  # Make sure to use the correct port

[[services]]
  internal_port = 3000   # The port your app is running on
  protocol = "tcp"
  ports = [{ port = 80 }]  # Publicly accessible port (for HTTP traffic)
